name: Java CI

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [1.15]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Setup environment variables
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build with Gradle
      run: gradle deployJar
    - name: Deploy Artifact Libs
      uses: actions/upload-artifact@v2
      with:
        name: runtime-libs-${{ matrix.os }}
        path: bin/lib
    - name: Deploy Artifact jarfile
      uses: actions/upload-artifact@v2
      with:
        name: nightly-${{ steps.vars.outputs.sha_short }}-${{ matrix.os }}
        path: bin/*.jar